FROM postgres:16-alpine

COPY migrations /migrations
COPY docker/run-migrations.sh /run-migrations.sh
COPY docker/init-roles.sql /docker/init-roles.sql

RUN chmod +x /run-migrations.sh

CMD ["/bin/sh", "/run-migrations.sh"]
